spring:
  application:
    name: product-service
  profiles:
    active: dev  
  config:
    # Config Server'dan yapılandırmaları almak için. optional çünkü Config Server çalışmazsa uygulamanın başlamasını engellememek için.
    import: "optional:configserver:http://localhost:8888"
server:
  port: 8082