spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/** 

server:
  port: 8888